version: '3.8'

services:
  proxy-rmq-web:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "5671:5671"
    env_file:
      - .env
  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:${WEB_PORT}"


