# Generated by Django 4.2.2 on 2023-11-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sensor_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
